src/TimetrackerBundle/Entity/Employee.php
<?php

namespace TimetrackerBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Employee
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class Employee
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="first_name", type="string", length=30)
     */
    private $firstName;

    /**
     * @var string
     *
     * @ORM\Column(name="last_name", type="string", length=30)
     */
    private $lastName;

    /**
     * @ORM\OneToMany(targetEntity="Card", mappedBy="employee")
     */
    protected $cards;

    /**
     * @ORM\OneToMany(targetEntity="Note", mappedBy="employee")
     */
    protected $notes;

    public function __construct()
    {
        $this->cards = new ArrayCollection();
        $this->notes = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set firstName
     *
     * @param string $firstName
     * @return Employee
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Get firstName
     *
     * @return string 
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Set lastName
     *
     * @param string $lastName
     * @return Employee
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * Get lastName
     *
     * @return string 
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Get Full Name
     *
     * @return string
     */
    public function getFullName()
    {
        return $this->firstName . ' ' . $this->lastName;
    }

    /**
     * Add cards
     *
     * @param TimetrackerBundle\Entity\Card $cards
     * @return Employee
     */
    public function addCard(\TimetrackerBundle\Entity\Card $cards)
    {
        $this->cards[] = $cards;

        return $this;
    }

    /**
     * Remove cards
     *
     * @param TimetrackerBundle\Entity\Card $cards
     */
    public function removeCard(\TimetrackerBundle\Entity\Card $cards)
    {
        $this->cards->removeElement($cards);
    }

    /**
     * Get cards
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getCards()
    {
        return $this->cards;
    }

    /**
     * Get logs
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getLogs()
    {
        $logs = new ArrayCollection;

        foreach ($this->getCards() as $card)
        {
            foreach ($card->getLogs() as $log)
            {
                $logs->add($log);
            }
        }

        return $logs;
    }

    /**
     * Add notes
     *
     * @param \TimetrackerBundle\Entity\Note $notes
     * @return Employee
     */
    public function addNote(\TimetrackerBundle\Entity\Note $notes)
    {
        $this->notes[] = $notes;

        return $this;
    }

    /**
     * Remove notes
     *
     * @param \TimetrackerBundle\Entity\Note $notes
     */
    public function removeNote(\TimetrackerBundle\Entity\Note $notes)
    {
        $this->notes->removeElement($notes);
    }

    /**
     * Get notes
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getNotes()
    {
        return $this->notes;
    }
}

src/TimetrackerBundle/Form/EmployeeType.php
<?php

namespace TimetrackerBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class EmployeeType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstName')
            ->add('lastName')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'TimetrackerBundle\Entity\Employee'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'timetrackerbundle_employee';
    }
}

src/TimetrackerBundle/Controller/EmployeeController.php
<?php

namespace TimetrackerBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use TimetrackerBundle\Entity\Employee;
use TimetrackerBundle\Form\EmployeeType;

/**
 * Employee controller.
 *
 * @Route("/employee")
 */
class EmployeeController extends Controller
{

    /**
     * Lists all Employee entities.
     *
     * @Route("/", name="employee")
     * @Method("GET")
     * @Template()
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $employees = $em->getRepository('TimetrackerBundle:Employee')->findAll();

        return array(
            'employees' => $employees,
        );
    }
    /**
     * Creates a new Employee entity.
     *
     * @Route("/", name="employee_create")
     * @Method("POST")
     * @Template("TimetrackerTimetrackerBundle:Employee:new.html.twig")
     */
    public function createAction(Request $request)
    {
        $entity = new Employee();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('employee_show', array('id' => $entity->getId())));
        }

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Creates a form to create a Employee entity.
     *
     * @param Employee $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(Employee $entity)
    {
        $form = $this->createForm(new EmployeeType(), $entity, array(
            'action' => $this->generateUrl('employee_create'),
            'method' => 'POST',
        ));

        return $form;
    }

    /**
     * Displays a form to create a new Employee entity.
     *
     * @Route("/new", name="employee_new")
     * @Method("GET")
     * @Template()
     */
    public function newAction()
    {
        $entity = new Employee();
        $form   = $this->createCreateForm($entity);

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Finds and displays a Employee entity.
     *
     * @Route("/{id}", name="employee_show")
     * @Method("GET")
     * @Template()
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $employee = $em->getRepository('TimetrackerBundle:Employee')->find($id);

        if (!$employee) {
            throw $this->createNotFoundException('Unable to find Employee entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return array(
            'employee'    => $employee,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Displays a form to edit an existing Employee entity.
     *
     * @Route("/{id}/edit", name="employee_edit")
     * @Method("GET")
     * @Template()
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $employee = $em->getRepository('TimetrackerBundle:Employee')->find($id);

        if (!$employee) {
            throw $this->createNotFoundException('Unable to find Employee entity.');
        }

        $editForm = $this->createEditForm($employee);
        $deleteForm = $this->createDeleteForm($id);

        return array(
            'employee'    => $employee,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
    * Creates a form to edit a Employee entity.
    *
    * @param Employee $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(Employee $entity)
    {
        $form = $this->createForm(new EmployeeType(), $entity, array(
            'action' => $this->generateUrl('employee_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        return $form;
    }
    /**
     * Edits an existing Employee entity.
     *
     * @Route("/{id}", name="employee_update")
     * @Method("PUT")
     * @Template("TimetrackerTimetrackerBundle:Employee:edit.html.twig")
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('TimetrackerBundle:Employee')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Employee entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $em->flush();

            return $this->redirect($this->generateUrl('employee_edit', array('id' => $id)));
        }

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }
    /**
     * Deletes a Employee entity.
     *
     * @Route("/{id}", name="employee_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('TimetrackerBundle:Employee')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Employee entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('employee'));
    }

    /**
     * Creates a form to delete a Employee entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('employee_delete', array('id' => $id)))
            ->setMethod('DELETE')
            ->getForm();
    }
}

src/TimetrackerBundle/Resources/views/Employee/edit.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Mitarbeiter bearbeiten</h1>
	
	{{ form_start(edit_form) }}
		
		<div class="form-group">
			{{ form_label(edit_form.firstName, 'Vorname') }}
			{{ form_errors(edit_form.firstName) }}
			{{ form_widget(edit_form.firstName, {'attr': {'class': 'form-control'}}) }}
		</div>
		<div class="form-group">
			{{ form_label(edit_form.lastName, 'Nachname') }}
			{{ form_errors(edit_form.lastName) }}
			{{ form_widget(edit_form.lastName, {'attr': {'class': 'form-control'}}) }}
		</div>

		<input type="submit" class="btn btn-primary" value="Änderungen speichern">
        <a href="{{ path('employee') }}" class="btn btn-default">Zurück</a>

	{{ form_end(edit_form) }}
    
    {{ form_start(delete_form) }}
    	<input type="submit" class="btn btn-danger pull-right" value="Mitarbeiter Löschen">
    {{ form_end(delete_form) }}

{% endblock %}

src/TimetrackerBundle/Resources/views/Employee/index.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Mitarbeiter</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Optionen</th>
            </tr>
        </thead>
        <tbody>
        {% for employee in employees %}
            <tr>
                <td><a href="{{ path('employee_show', { 'id': employee.id }) }}">{{ employee.fullName }}</a></td>
                <td>
                    <a href="{{ path('calendar_show', {
                    'employee': employee.id,
                    'year': 'now'|date('Y'),
                    'month': 'now'|date('m') })}}">Kalender</a> | 
                    <a href="{{ path('employee_edit', { 'id': employee.id }) }}">Bearbeiten</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="{{ path('employee_new') }}" class="btn btn-primary">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Mitarbeiter hinzufügen
    </a>
{% endblock %}

src/TimetrackerBundle/Resources/views/Employee/new.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Employee creation</h1>

	{{ form_start(form) }}
		
		<div class="form-group">
			{{ form_label(form.firstName, 'Vorname') }}
			{{ form_errors(form.firstName) }}
			{{ form_widget(form.firstName, {'attr': {'class': 'form-control'}}) }}
		</div>
		<div class="form-group">
			{{ form_label(form.lastName, 'Nachname') }}
			{{ form_errors(form.lastName) }}
			{{ form_widget(form.lastName, {'attr': {'class': 'form-control'}}) }}
		</div>

		<input type="submit" class="btn btn-primary" value="Erstellen">
        <a href="{{ path('employee') }}" class="btn btn-default">Zurück</a>

	{{ form_end(form) }}
	
{% endblock %}

src/TimetrackerBundle/Resources/views/Employee/show.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>{{ employee.fullName }}</h1>
    
    <dl class="dl-horizontal">
        <dt>Id</dt>
        <dd>{{ employee.id }}</dd>
        <dt>Vorname</dt>
        <dd>{{ employee.firstName }}</dd>
        <dt>Nachname</dt>
        <dd>{{ employee.lastName }}</dd>
        <dt>Karten</dt>
        {% for card in employee.cards %}
            <dd>{{ card.signature }}</dd>
        {% endfor %}
    </dl>
    <a href="{{ path('employee_edit', { 'id': employee.id }) }}" class="btn btn-primary">
        Bearbeiten
    </a>
    <a href="{{ path('employee') }}" class="btn btn-default">
        Zurück
    </a>
{% endblock %}